### PR TITLE
adds default slot to seq panel

### PR DESCRIPTION
**Pull request by bulbil**
The issue is that we would like to place controls in a `sequence-panel`, ideally using exactly the same api as `canvas-panel` which accepts a default slot (c.f., https://iiif-canvas-panel.netlify.app/docs/applications/simple-viewer-with-common-features).

It may be that I'm missing something but I thought I would try with comically simple, naive approach in case that would suffice. I did a quick test in storybook and it appears to work as expected.

### CODE REVIEW

**Comment by stephenwf** [comment]
@bulbil Excellent, thanks for the contribution! There is a pre-release version released using codesandbox that you can test with. But let me know if you need a proper patch on NPM.

**Comment by bulbil** [comment]
@stephenwf we would need a version to include in a package we are developing -- I don't believe you can do that with codesandbox (as far as I know). A patch would be great!

**Comment by stephenwf** [comment]
@bulbil If it's still in development, I would recommend using the preview package.
Full details can be found here: https://ci.codesandbox.io/status/digirati-co-uk/iiif-canvas-panel/pr/233/builds/458278

If you are using a package manager:
```
# yarn 1
yarn add https://pkg.csb.dev/digirati-co-uk/iiif-canvas-panel/commit/dda431b6/@digirati/canvas-panel-web-components
# yarn 2, 3
yarn add @digirati/canvas-panel-web-components@https://pkg.csb.dev/digirati-co-uk/iiif-canvas-panel/commit/dda431b6/@digirati/canvas-panel-web-components/_pkg.tgz
# npm
npm i https://pkg.csb.dev/digirati-co-uk/iiif-canvas-panel/commit/dda431b6/@digirati/canvas-panel-web-components
```

Or if you want to use the bundle directly:
```
https://pkg.csb.dev/digirati-co-uk/iiif-canvas-panel/commit/dda431b6/@digirati/canvas-panel-web-components/dist/bundle.js
```

**Comment by bulbil** [comment]
@stephenwf works for us, I was unfamiliar with codesandbox pr builds.

**Comment by stephenwf** [comment]
That's great! It just gives you a bit more flexibility if you open a PR that you want to test immediately. Codesandbox should publish those preview packages for all commits.

**Pull request merged**
