### PR TITLE
Sequence Panel: Add Eventlistener to display annotations

### PR DESCRIPTION
**Pull request by bulbil**
I am having trouble creating event listeners on display annotations with multiple canvases in sequence panel. I've created a story to illustrate the issue.

### Expected

Iterating through a list and a) creating display annotations, b) adding event listeners, and c) adding those new annotations into vault should add event listeners on each annotation.

I should click on either annotation and an event should fire.

### Observed

The event listener is added only to the annotations on the first canvas in the sequence. I realize this story only has a single annotation on the first (left) canvas but this works as expected when the left canvas has multiple annotations.

Seems not dissimilar to the issue where makeChoice was exclusively being applied to the left canvas in a sequence?

### CODE REVIEW

**Comment by stephenwf** [comment]
@bulbil I'm not sure exactly what the bug was, but I've seen it before with `<box />` elements inside of `<world-object />` (or more specifically, the `<ResizeWorldObject/>`).

I moved the event to the `world-object` consistently, so the clicks should be working. I might look at tracking down the issue with the `<box />` event, but I don't think it's worth the effort at the moment. [The experimental refactor](https://github.com/atlas-viewer/atlas/blob/main/src/__tests__/clean-objects/traits/evented.tests.ts) should solve this. 

Also added some new APIs at the WebComponent level:

```ts
sequencePanel.addVaultEventListener(resource, 'onClick', handler);
sequencePanel.removeVaultEventListener(resource, 'onClick', handler);
sequencePanel.getListenersAsProps(resource); // { onClick: [Function], ... }
```

Which should help adding events, but also debugging - so you can access the event helper.

**Comment by bulbil** [comment]
@stephenwf oh great, thanks for looking into this. I able to attach events as expected now. 

It is a little unusual because the left canvas in the sequence fires the event 2x whereas the right canvas fires the same event 4x.

@abrin we can now attach events and generate clickable annotations.

**Comment by abrin** [comment]
@bulbil this sounds like what I was seeing with the `ViewCanvas` where it seemed like an event was being fired per-choice I believe, hence the duplication. Might be something similar here if you're seeing similar events?

**Comment by stephenwf** [comment]
@bulbil @abrin I've merged the main branch, hoping that fixes the Netlify build

**Comment by stephenwf** [comment]
The storybook is failing 🙄 with some obscure error. Given the success of the [Vite based](https://atlas-viewer-storybook.netlify.app/) replacement on Atlas, which was a 5 year old codebase.. I'll look at doing the same thing for this repository.

**Pull request merged**
