### PR TITLE
Updated atlas version

### PR DESCRIPTION
**Pull request by stephenwf**

### CODE REVIEW

**Comment by stephenwf** [comment]
@abrin Something not quite right.
https://deploy-preview-263--iiif-canvas-panel-demos.netlify.app/

It doesn't look like its hitting the ready state at all.

**Comment by danieltbrennan** [comment]
> @abrin Something not quite right. https://deploy-preview-263--iiif-canvas-panel-demos.netlify.app/
> 
> It doesn't look like its hitting the ready state at all.

I see what the issue is here in Atlas, I forgot to push a commit 😞 . https://github.com/atlas-viewer/atlas/pull/51

**Comment by stephenwf** [comment]
@abrin that's working now 🎉 

Do you want me to merge this and #262 and get a release?

**Comment by abrin** [comment]
@stephenwf just this, I think. We were talking at standup and it seems like the `a11yTitle` isn't updating after the initial value is passed, Jason's looking at that.  thanks!

**Comment by stephenwf** [comment]
@abrin you can set the `aria-label=""` on the `<canvas-panel>` or `<sequence-panel>` directly, if that helps at all.

**Comment by stephenwf** [comment]
```
+ @digirati/canvas-panel-web-components@1.0.65
```
🎉

**Pull request merged**
