### PR TITLE
clean build of touch interactions

### PR DESCRIPTION
**Pull request by abrin**
this provides a clean build of the updated atlas logic with the approprate attributes to enable/disable the touch-interaction features.

### CODE REVIEW

**Review by stephenwf — APPROVED** [review]
Great 👍 

Builds are still failing for storybook - on my list to take a closer look at.

**Comment by abrin** [comment]
@stephenwf is it possible to check if in Netlify the build is set to use node 16 or an older version? My guess is that's the core source of the issue
Screenshot 2024-06-18 at 2 43 41 PM

**Comment by stephenwf** [comment]
I've tried that - but I _think_ most dependencies now require higher than 16. Need to update the broken dependencies. Let's see what the build does 👍

**Comment by stephenwf** [comment]
Hmm, it seemed to ignore the change to the netlify config - still used v18 (.nvmrc?)

**Comment by stephenwf** [comment]
Do you want to merge this now? I'll look at the storybook later

**Comment by abrin** [comment]
I _think_ we're ready here if you are

**Comment by abrin** [comment]
> I've tried that - but I _think_ most dependencies now require higher than 16. Need to update the broken dependencies. Let's see what the build does 👍

sorry, was just spitballing

**Comment by stephenwf** [comment]
Published as `@digirati/canvas-panel-web-components@1.0.67` 🎉

**Comment by abrin** [comment]
thank you!

**Pull request merged**
